### ISSUE TITLE
The buttons under Pre Processing need to be large to show the text, particularly for mac.

### ISSUE THREAD

**Issue by sichendart** [tomography/XRFtomo#47]

**Comment by FabricioSMarin** [comment]
Button sizes are now larger. Under each of the ..._controls.py files, right below the initUI() function, there are button size definitions that can be changed. I’m not sure of the best way to set these values so they are hard-coded to a slightly larger value than before for now.

**Comment by sichendart** [comment]
Looks fine now. Thanks.
