### ISSUE TITLE
name of the repository

### ISSUE THREAD

**Issue by sichendart** [tomography/XRFtomo#51]
@decarlof, please change it to XRFtomo. Please also update the command to start software etc. to be consistent.

**Comment by decarlof** [comment]
I addressed this in #53. This t is quite disruptive to the existing forks (after it is accepted you will not be able to merge your fork automatically). I suggest to review/accept #53 as soon as possible, or at least before changes are made in your forks.
Once accepted you should delete your fork and create a new one, before continuing working on the code. Please let me know if there is any issue

**Comment by sichendart** [comment]
I deleted my old fork, and created a new one from tomography/XRFtomo. Seems working fine now. I changed the main window title to XRFtomo too. @decarlof shall we also change the commands, for example, "xfluo gui" to "XRFtomo gui" in order to be consistent?

**Comment by xray-imaging** [comment]
@sichendart your fork is not from the new project (renamed version) until @FabricioSMarin reviews and accepts the pull request at #53

**Comment by decarlof** [comment]
@sichendart your fork is not from the new version (renamed protect name) until @FabricioSMarin reviews and accepts the pull request at #53. The new version renames xfluo into XRFtomo everywhere (including the main window title). Once accepted please delete and make a new fork.

**Comment by FabricioSMarin** [comment]
How do I accept pull request #53 ?

**Comment by decarlof** [comment]
you should have received a while ago an invitation to be a collaborator and more recently a request to review the pull request. You should also be able to directly merge the pull request after review.
I will be re-sending the invitation right now

**Comment by FabricioSMarin** [comment]
Thank you. In order to delete my fork. Is this done under options>'delete this repository'?  
![Screenshot from 2020-02-10 10-49-37](https://user-images.githubusercontent.com/20801183/74172832-898d5380-4bf6-11ea-9c72-7b61069c8f6e.png)

**Comment by decarlof** [comment]
that is correct. You are in sync except the xfluo to xrftomo name change, so it is save to delete and refork
