### ISSUE TITLE
xfluo init

### ISSUE THREAD

**Issue by sichendart** [tomography/XRFtomo#57]
It seems that "xfluo init" starts the software unintendedly; I do not see "init" listed as an argument when do "xfluo --help".

**Comment by decarlof** [comment]
should it be:
```
xrftomo init

```
?

**Comment by decarlof** [comment]
I also suggest to uninstall xfluo with:

```
$ pip uninstall xfluo
```

**Comment by sichendart** [comment]
OK. I just uninstalled it. Thanks.
